variable "env" {}
variable "vpc_public_cidr" {}
variable "vpc_private_cidr" {}
variable "subnet_public_cidr" {}
variable "subnet_private_cidr" {}
variable "AZS" {}
variable "default_vpc" {}
variable "default_vpc_cidr" {}
variable "default_RT_id" {}